In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [5]:
df=pd.read_csv('/content/drive/MyDrive/covid_toy.csv')
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [8]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [7]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

# **Aam Zindagi**

In [10]:
x=df.iloc[:,:-1]
y=df['has_covid']

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x_train,x_test,y_train,y_train=train_test_split(x,y,test_size=0.2,random_state=42)

In [20]:
# Adding simple imputer to fever col
si=SimpleImputer()
x_train_fever=si.fit_transform(x_train[['fever']])

# also the test data
x_test_fever=si.fit_transform(x_test[['fever']])

x_train_fever.shape

(80, 1)

In [24]:
# ordinal encoding-----> cough
oe=OrdinalEncoder(categories=[['Mild','Strong']])
x_train_cough=oe.fit_transform(x_train[['cough']])

x_test_cough=oe.fit_transform(x_test[['cough']])

x_train_cough.shape

(80, 1)

In [28]:
# onehot Encoding-----> Gender, city
ohe= OneHotEncoder(drop='first',sparse_output=False)
x_train_gender_city=ohe.fit_transform(x_train[['gender','city']])

x_test_gender_city=ohe.fit_transform(x_test[['gender','city']])

x_train_gender_city.shape

(80, 4)

In [29]:
# Extracting age
x_train_age=x_train.drop(columns=['gender','fever','cough','city']).values

x_test_age=x_test.drop(columns=['gender','fever','cough','city']).values

x_train_age.shape

(80, 1)

In [32]:
cf=np.concatenate((x_train_age,x_train_fever,x_train_gender_city,x_train_cough),axis=1)
cf.shape

(80, 7)

# Mentos Ki Zindagi

In [34]:
from sklearn.compose import ColumnTransformer

In [37]:
transformer=ColumnTransformer(transformers=[
    ("tfn1",SimpleImputer(),['fever']),
    ("tfn2",OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ("tfn3",OneHotEncoder(drop='first',sparse_output=False),['gender','city'])
    ],remainder='passthrough')

In [42]:
transformer.fit_transform(x_train).shape

(80, 7)

In [43]:
transformer.fit_transform(x_test).shape

(20, 7)

In [33]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No